### ISSUE TITLE
Fail gracefully when download build file missing from URL

### ISSUE THREAD

**Issue by rpappalax** [mozilla/ff-tool#85]
---
## DOWNLOAD FIREFOX

Downloading nightly to _temp/browsers/FirefoxNightly.dmg
Traceback (most recent call last):
  File "/Users/rpappalardo/git/tmp/venv/bin/ff", line 11, in <module>
    sys.exit(main())
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/fftool/main.py", line 29, in main
    download(options.channel)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/fftool/firefox_download.py", line 58, in download
    platform=ch_platform
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/factory.py", line 125, in __init__
    scraper_types[scraper_type].**init**(self, *_kwargs)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 344, in **init**
    Scraper.**init**(self, *args, *_kwargs)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 133, in **init**
    self._retry_check_404(self.get_build_info)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 148, in _retry_check_404
    self._retry(func, *_retry_kwargs)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 139, in _retry
    return redo.retry(func, *_retry_kwargs)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/redo/__init__.py", line 152, in retry
    return action(_args, *_kwargs)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 401, in get_build_info
    self.date, self.build_index)
  File "/Users/rpappalardo/git/tmp/venv/lib/python2.7/site-packages/mozdownload/scraper.py", line 482, in get_build_info_for_date
    raise errors.NotFoundError(message, url)
mozdownload.errors.NotFoundError: Folder for builds on 2016-05-27-12-50-00 has not been found: https://archive.mozilla.org/pub/firefox/nightly/2016/05/

**Comment by pdehaan** [comment]
You lost me.
Is this something wrong with a config file? Or just no daily build on the server (and this is just more of a builds/mozdownload issue we're trying to defend against)?

**Comment by rpappalax** [comment]
Apparently today there's no nightly build found at this link. I guess that may happen from time-to-time.  Would like to fail gracefully when that happens and/or offer the user the opportunity to use the Nightly dmg they may already have downloaded or installed.  
I currently have a Nightly cached, but because mozdownload chokes at this point, the script just stops.  
which is bad.

**Comment by pdehaan** [comment]
Yeah, sounds good.
Probably wrap the mozdownloaden code in a `try..except` and then display an error and fallback to cached copy and fail hard if we can't resolve from a cache.
